import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TrpcProvider from "@/_server/TrpcProvider";
import { Toaster } from "sonner";
import { SettingsProvider } from "@/_client/1_app/providers/with-settings";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} dark bg-background antialiased`}
      >
        <Toaster />
        <TrpcProvider>
          <SettingsProvider userId="00802fab-e266-4e1b-a24a-e3cff1cba2c5">
            {children}
          </SettingsProvider>
        </TrpcProvider>
      </body>
    </html>
  );
}
